
# This is a basic workflow that is manually triggered

name: github_insights_etl
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas flatten_json google-cloud-bigquery 
    - name: Run github etl script
      env:
        private_key: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo ${{ secrets.PRIVATE_KEY }}>>private_key.json
        python authorization.py
