# This is a basic workflow that is manually triggered

name: ga4_google_analytics_etl
on:
  workflow_dispatch:
  schedule:
    - cron: 30 7 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ga4-etl:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas google-cloud-bigquery pyarrow google-analytics-data
        
    - name: Authorize google cloud 
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_ANALYTICS_API_SERVICE_ACCOUNT}}'
    - name: Run github etl script        
      run: |
        python src/pythonScripts/googleAnalytics/googleAnalyticsApiGa4Only.py
