# This is a basic workflow that is manually triggered

name: github_insights_etl
on:
  workflow_dispatch:
  schedule:
    - cron: 30 1 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-etl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas flatten_json google-cloud-bigquery pyarrow
        
    - name: Authorize google cloud 
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/541809542441/locations/global/workloadIdentityPools/superset-pools/providers/github-superset'
        service_account: 'superset@idc-external-025.iam.gserviceaccount.com'
    - name: Run github etl script        
      env:
        user_name: ${{ secrets.USER_NAME }}
        github_token: ${{ secrets.API_TOKEN }}
      run: |
        python gh_insights_etl.py
        
