# This is a basic workflow that is manually triggered

name: github_insights_etl
on:
  workflow_dispatch:
  schedule:
    - cron: 30 1 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-etl:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas flatten_json google-cloud-bigquery pyarrow
        
    - name: Authorize google cloud 
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_ANALYTICS_API_SERVICE_ACCOUNT}}'
        
    - name: Run github etl script        
      env:
        user_name: ${{ secrets.USER_NAME }}
        github_token: ${{ secrets.API_TOKEN }}
      run: |
        python src/pythonScripts/github/gh_insights_etl.py
        
