# This is a basic workflow that is manually triggered

name: github_insights_etl
on:
  schedule:
    - cron: "0 1 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas flatten_json
        python --version
        ls .
    - name: Run github etl script
      env:
        user_name: ${{ secrets.USER_NAME }}
        github_token: ${{ secrets.API_TOKEN }}
      run: |
        python --version
        python gh_insights_etl.py
        
