# This is a basic workflow that is manually triggered

name: identity federation
on:
  workflow_dispatch:
  schedule:
    - cron: 30 1 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-etl:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Authorize google cloud 
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/452372932426/locations/global/workloadIdentityPools/superset-pool/providers/superset'
        service_account: 'superset-service-account@superset-gke.iam.gserviceaccount.com'
