name: keep-github-actions-alive

on:
    schedule:
      - cron: "0 0 * * *"  
jobs:
    keep-alive:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: gautamkrishnar/keepalive-workflow@v2
            with:
                time_elapsed: 50
                use_api: False
